# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "star_rating"
pin "shop_image_preview"
pin "icon_preview"
pin "tags"
pin "toggle_search"
pin "search_tags"
pin "toggle_tabs"
pin "map", to: "map.js"