// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "star_rating"
import "shop_image_preview"
import "icon_preview"
import "tags"
import "toggle_search"
import "search_tags"
import "toggle_tabs"
import "map"